name: base
channels:
  - conda-forge
dependencies:
  - archspec=0.2.3=pyhd8ed1ab_0
  - boltons=24.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py310h00ffb61_1
  - bzip2=1.0.8=hcfcfb64_5
  - ca-certificates=2024.2.2=h56e8100_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h8d17308_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - conda=24.3.0=py310h5588dad_0
  - conda-libmamba-solver=24.1.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_0
  - fmt=10.2.1=h181d51b_0
  - idna=3.6=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py310h5588dad_3
  - krb5=1.21.2=heb0366b_0
  - libarchive=3.7.2=h313118b_1
  - libcurl=8.7.1=hd5e4a3a_0
  - libffi=3.4.2=h8ffe710_5
  - libiconv=1.17=hcfcfb64_2
  - libmamba=1.5.8=h3f09ed1_0
  - libmambapy=1.5.8=py310h04f2035_0
  - libsolv=0.7.28=h12be248_2
  - libsqlite=3.45.2=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libxml2=2.12.6=hc3477c8_1
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=hcfcfb64_0
  - lzo=2.10=he774522_1000
  - mamba=1.5.8=py310hd9d798f_0
  - menuinst=2.0.2=py310h00ffb61_0
  - miniforge_console_shortcut=1.0=h57928b3_0
  - openssl=3.2.1=hcfcfb64_1
  - packaging=24.0=pyhd8ed1ab_0
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py310h8d17308_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.14=h4de0772_0_cpython
  - python_abi=3.10=4_cp310
  - reproc=14.2.4.post0=hcfcfb64_1
  - reproc-cpp=14.2.4.post0=h63175ca_1
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel.yaml=0.18.6=py310h8d17308_0
  - ruamel.yaml.clib=0.2.8=py310h8d17308_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tqdm=4.66.2=pyhd8ed1ab_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.3=hcf57466_18
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.43.0=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xz=5.2.6=h8d14728_0
  - yaml-cpp=0.8.0=h63175ca_0
  - zstandard=0.22.0=py310h0009e47_0
  - zstd=1.5.5=h12be248_0
prefix: c:\software\conda
